### ISSUE TITLE
the simulation of stefan problem 1

### ISSUE THREAD

**Issue by HOMEN-ZHENG-25** [wyldckat/evapVOFHardt#3]
hello M.Sc. Stefan Batzdorf：
      Now i want to simulate the stefan problem 1 in this article（S. Hardt, F. Wondra, 2008. Evaporation model for interfacial flows based on a continuum-field representation of source terms, Journal of Computational Physics, vol. 227, pp. 5871-5895.），but i failed because the data never matched.So i want to know some reason.Can you tell me？
Thank you.

**Comment by wyldckat** [comment]
Greetings @HOMEN-ZHENG-25 

Unfortunately I do not know the email address for Stefan Batzdorf and I only handled the adaptation of the code to work on OpenFOAM 2.2.x and 2.3.x. I have no experience with this solver and the work behind it :(

I've now updated the README file and added a link to a snapshot of the original webpage: http://web.archive.org/web/20170419224010/www.ttd.tu-darmstadt.de/forschung_1/openfoamdatenbank/evapvofhard.en.jsp

If you check the thread I mentioned in the README file, there are links there to other forum threads. The latest one that seems to discuss this is this one: https://www.cfd-online.com/Forums/openfoam-solving/156965-validation-evapvofhardt.html - and there they mentioned that perhaps it would be best to use another implementation that was suggested there.
